
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zenika
    username: root
    password: root
    driver-classname: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: 0d48e5d7ea7011
    password: 8c6c6355a65e04
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true